algoritmo "Estrutura-PAra-Faca"
// Função :
// Autor :
// Data : 23/07/2022
// Seção de Declarações 
var

   numero, fatorial, cont: inteiro
inicio
// Seção de Comandos 

   escreva("Digite o número desejado para calcular o fatorial!! ")
   leia(numero)
   fatorial := 1
   para cont de 1 ate numero faca
        fatorial := fatorial * cont
   fimpara
   
   escreva("O fatorial de ",numero, "e:", fatorial)
fimalgoritmo
